name: CI Check Pipeline Integration

on: 
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches:
      - ruhul
      - feature/ruhul-cs
      - feature/atik
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm run test
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build --network=host -t my-app:test .

      - name: Run container to check health
        run: |
          docker run --rm my-app:test echo "Container is running"
  notify:
    name: Notify on Merge to Main
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Notify Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content":"Unit Testing Completed"}' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
